services:
  - type: web
    name: crypto-price-predictor
    env: docker
    plan: free
    region: ohio
    buildCommand: docker build -t backend .
    startCommand: docker run -p 8080:8080 backend
    envVars:
      - key: PORT
        value: 8080
      - key: PYTHON_VERSION
        value: 3.10.12
